// Code generated by goctl. DO NOT EDIT.
package types

type Request struct {
	Name string `path:"name,options=you|me"`
}

type Response struct {
	Message string `json:"message"`
}

type UserRequest struct {
	Id int64 `path:"id"`
}

type UserResponse struct {
	Message map[int64]string `json:"message"`
}

type UserListResponse struct {
	Message map[int64]string `json:"message"`
}
